// <auto-generated />
using System;
using System.Net;
using Buttercup.EntityModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Buttercup.EntityModel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261010201041_BaselineSchema")]
    partial class BaselineSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:und-ci", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Buttercup.EntityModel.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body")
                        .UseCollation("und-ci");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipe_id");

                    b.Property<int>("UpdateCount")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("update_count");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comments_author_id");

                    b.HasIndex("Deleted")
                        .HasDatabaseName("ix_comments_deleted");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("ix_comments_deleted_by_user_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_comments_recipe_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Buttercup.EntityModel.CommentAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("action")
                        .UseCollation("C");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_id");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<long?>("RevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("revision_id");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("pk_comment_audits");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_comment_audits_actor_id");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_comment_audits_comment_id");

                    b.HasIndex("RevisionId")
                        .HasDatabaseName("ix_comment_audits_revision_id");

                    b.ToTable("comment_audits", (string)null);
                });

            modelBuilder.Entity("Buttercup.EntityModel.CommentRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body")
                        .UseCollation("und-ci");

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_id");

                    b.HasKey("Id")
                        .HasName("pk_comment_revisions");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_comment_revisions_comment_id");

                    b.ToTable("comment_revisions", (string)null);
                });

            modelBuilder.Entity("Buttercup.EntityModel.PasswordResetToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("token")
                        .UseCollation("C");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Token")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Buttercup.EntityModel.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CookingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cooking_minutes");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredients")
                        .UseCollation("und-ci");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method")
                        .UseCollation("und-ci");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<long?>("ModifiedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_user_id");

                    b.Property<int?>("PreparationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("preparation_minutes");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .UseCollation("und-ci");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.Property<string>("Source")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("source")
                        .UseCollation("und-ci");

                    b.Property<string>("Suggestions")
                        .HasColumnType("text")
                        .HasColumnName("suggestions")
                        .UseCollation("und-ci");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title")
                        .UseCollation("und-ci");

                    b.Property<int>("UpdateCount")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("update_count");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_recipes_created");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_recipes_created_by_user_id");

                    b.HasIndex("Deleted")
                        .HasDatabaseName("ix_recipes_deleted");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("ix_recipes_deleted_by_user_id");

                    b.HasIndex("Modified")
                        .HasDatabaseName("ix_recipes_modified");

                    b.HasIndex("ModifiedByUserId")
                        .HasDatabaseName("ix_recipes_modified_by_user_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_recipes_title");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Buttercup.EntityModel.RecipeAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("action")
                        .UseCollation("C");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipe_id");

                    b.Property<long?>("RevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("revision_id");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("pk_recipe_audits");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_recipe_audits_actor_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_audits_recipe_id");

                    b.HasIndex("RevisionId")
                        .HasDatabaseName("ix_recipe_audits_revision_id");

                    b.ToTable("recipe_audits", (string)null);
                });

            modelBuilder.Entity("Buttercup.EntityModel.RecipeRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CookingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cooking_minutes");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredients")
                        .UseCollation("und-ci");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method")
                        .UseCollation("und-ci");

                    b.Property<int?>("PreparationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("preparation_minutes");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .UseCollation("und-ci");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.Property<string>("Source")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("source")
                        .UseCollation("und-ci");

                    b.Property<string>("Suggestions")
                        .HasColumnType("text")
                        .HasColumnName("suggestions")
                        .UseCollation("und-ci");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title")
                        .UseCollation("und-ci");

                    b.HasKey("Id")
                        .HasName("pk_recipe_revisions");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_revisions_recipe_id");

                    b.ToTable("recipe_revisions", (string)null);
                });

            modelBuilder.Entity("Buttercup.EntityModel.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Deactivated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("email")
                        .UseCollation("und-ci");

                    b.Property<string>("HashedPassword")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("hashed_password")
                        .UseCollation("C");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name")
                        .UseCollation("und-ci");

                    b.Property<DateTime?>("PasswordCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_created");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("security_stamp")
                        .UseCollation("C");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("time_zone")
                        .UseCollation("C");

                    b.Property<int>("UpdateCount")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("update_count");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_users_created");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Modified")
                        .HasDatabaseName("ix_users_modified");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_users_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Buttercup.EntityModel.UserAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<string>("Failure")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("failure")
                        .UseCollation("C");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("operation")
                        .UseCollation("C");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("pk_user_audit_entries");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_user_audit_entries_actor_id");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_user_audit_entries_target_id");

                    b.HasIndex("Time")
                        .HasDatabaseName("ix_user_audit_entries_time");

                    b.ToTable("user_audit_entries", (string)null);
                });

            modelBuilder.Entity("Buttercup.EntityModel.Comment", b =>
                {
                    b.HasOne("Buttercup.EntityModel.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("fk_comments_users_author_id");

                    b.HasOne("Buttercup.EntityModel.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .HasConstraintName("fk_comments_users_deleted_by_user_id");

                    b.HasOne("Buttercup.EntityModel.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_recipes_recipe_id");

                    b.Navigation("Author");

                    b.Navigation("DeletedByUser");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Buttercup.EntityModel.CommentAudit", b =>
                {
                    b.HasOne("Buttercup.EntityModel.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .HasConstraintName("fk_comment_audits_users_actor_id");

                    b.HasOne("Buttercup.EntityModel.Comment", "Comment")
                        .WithMany("Audits")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_audits_comments_comment_id");

                    b.HasOne("Buttercup.EntityModel.CommentRevision", "Revision")
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .HasConstraintName("fk_comment_audits_comment_revisions_revision_id");

                    b.Navigation("Actor");

                    b.Navigation("Comment");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Buttercup.EntityModel.CommentRevision", b =>
                {
                    b.HasOne("Buttercup.EntityModel.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_revisions_comments_comment_id");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Buttercup.EntityModel.PasswordResetToken", b =>
                {
                    b.HasOne("Buttercup.EntityModel.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Buttercup.EntityModel.Recipe", b =>
                {
                    b.HasOne("Buttercup.EntityModel.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("fk_recipes_users_created_by_user_id");

                    b.HasOne("Buttercup.EntityModel.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .HasConstraintName("fk_recipes_users_deleted_by_user_id");

                    b.HasOne("Buttercup.EntityModel.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .HasConstraintName("fk_recipes_users_modified_by_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("Buttercup.EntityModel.RecipeAudit", b =>
                {
                    b.HasOne("Buttercup.EntityModel.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .HasConstraintName("fk_recipe_audits_users_actor_id");

                    b.HasOne("Buttercup.EntityModel.Recipe", "Recipe")
                        .WithMany("Audits")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_audits_recipes_recipe_id");

                    b.HasOne("Buttercup.EntityModel.RecipeRevision", "Revision")
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .HasConstraintName("fk_recipe_audits_recipe_revisions_revision_id");

                    b.Navigation("Actor");

                    b.Navigation("Recipe");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Buttercup.EntityModel.RecipeRevision", b =>
                {
                    b.HasOne("Buttercup.EntityModel.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_revisions_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Buttercup.EntityModel.UserAuditEntry", b =>
                {
                    b.HasOne("Buttercup.EntityModel.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_audit_entries_users_actor_id");

                    b.HasOne("Buttercup.EntityModel.User", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_audit_entries_users_target_id");

                    b.Navigation("Actor");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Buttercup.EntityModel.Comment", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("Buttercup.EntityModel.Recipe", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
