DROP DATABASE IF EXISTS `{DatabaseName}`;
CREATE DATABASE `{DatabaseName}` DEFAULT CHARACTER SET utf8;
USE `{DatabaseName}`;

CREATE TABLE recipe (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  preparation_minutes SMALLINT UNSIGNED,
  cooking_minutes SMALLINT UNSIGNED,
  servings SMALLINT UNSIGNED,
  ingredients TEXT NOT NULL,
  method TEXT NOT NULL,
  suggestions TEXT,
  remarks TEXT,
  source VARCHAR(255),
  created DATETIME NOT NULL,
  modified DATETIME NOT NULL,
  revision SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE user (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(250) NOT NULL,
  hashed_password CHAR(84),
  created DATETIME NOT NULL,
  modified DATETIME NOT NULL,
  revision SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY user_u1 (email)
) ENGINE=InnoDB;
