name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      WEB_PROJECT_PATH: src/Buttercup.Web
    permissions:
      attestations: write
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.1xx
          dotnet-quality: ga
      - name: Publish
        run: dotnet publish Buttercup.Web.csproj --configuration Release --os linux --arch x64 /t:PublishContainer -p ContainerRepository=$IMAGE_NAME
        working-directory: ${{env.WEB_PROJECT_PATH}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Inspect image
        run: docker image inspect $IMAGE_NAME:latest
      - name: Push
        run: |
          docker tag $IMAGE_NAME $REGISTRY/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME $REGISTRY/$IMAGE_NAME:commit-$GITHUB_SHA
          docker push --all-tags $REGISTRY/$IMAGE_NAME
      - name: More debug
        run: docker images $REGISTRY/$IMAGE_NAME:latest --digests
