name: Publish Container
on: workflow_dispatch
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      WEB_PROJECT_PATH: src/Buttercup.Web
    permissions:
      attestations: write
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.1xx
          dotnet-quality: ga
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: ${{env.WEB_PROJECT_PATH}}/package-lock.json
      - name: Restore Node.js dependencies
        run: npm ci
        working-directory: ${{env.WEB_PROJECT_PATH}}
      - name: Build assets
        run: npx gulp build
        working-directory: ${{env.WEB_PROJECT_PATH}}
      - name: Build container
        run: |
          dotnet publish Buttercup.Web.csproj \
            -t PublishContainer \
            -p ContainerFamily=noble-chiseled-extra \
            -p ContainerRepository=$IMAGE_NAME \
            -p RuntimeIdentifiers='"linux-x64;linux-arm64"' \
            -p LocalRegistry=Podman
        working-directory: ${{env.WEB_PROJECT_PATH}}
      - name: Create multi-architecture manifest
        run: |
          podman manifest create $IMAGE_NAME:latest
          podman manifest add $IMAGE_NAME:latest containers-storage:localhost/$IMAGE_NAME:latest-linux-arm64
          podman manifest add $IMAGE_NAME:latest containers-storage:localhost/$IMAGE_NAME:latest-linux-x64
      - name: Log in GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Container Registry
        run: |
          podman push localhost/$IMAGE_NAME:latest-linux-arm64 docker://$REGISTRY/$IMAGE_NAME:latest-linux-arm64 --digestfile digest
          podman push localhost/$IMAGE_NAME:latest-linux-arm64 docker://$REGISTRY/$IMAGE_NAME:$GITHUB_SHA-linux-arm64
          echo "$(cat digest | sed 's/sha256://')  $REGISTRY/$IMAGE_NAME" >> digests
          podman push localhost/$IMAGE_NAME:latest-linux-x64 docker://$REGISTRY/$IMAGE_NAME:latest-linux-x64 --digestfile digest
          podman push localhost/$IMAGE_NAME:latest-linux-x64 docker://$REGISTRY/$IMAGE_NAME:$GITHUB_SHA-linux-x64
          echo "$(cat digest | sed 's/sha256://')  $REGISTRY/$IMAGE_NAME" >> digests
          podman push localhost/$IMAGE_NAME:latest docker://$REGISTRY/$IMAGE_NAME:latest --digestfile digest
          podman push localhost/$IMAGE_NAME:latest docker://$REGISTRY/$IMAGE_NAME:$GITHUB_SHA
          echo "$(cat digest | sed 's/sha256://')  $REGISTRY/$IMAGE_NAME" >> digests
      - name: Attest provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-checksums: digests
