name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      WEB_PROJECT_PATH: src/Buttercup.Web
    permissions:
      attestations: write
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.1xx
          dotnet-quality: ga
      - name: Publish
        run: dotnet publish Buttercup.Web.csproj --configuration Release --os linux --arch x64 /t:PublishContainer -p ContainerRepository=$IMAGE_NAME -p LocalRegistry=Podman
        working-directory: ${{env.WEB_PROJECT_PATH}}
      - name: Check digest
        run: podman images $IMAGE_NAME --format "{{.Digest}}"
