name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      WEB_PROJECT_PATH: src/Buttercup.Web
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.1xx
          dotnet-quality: ga
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{env.WEB_PROJECT_PATH}}/package-lock.json
      - name: Restore Node.js dependencies
        run: npm ci
        working-directory: ${{env.WEB_PROJECT_PATH}}
      - name: Build assets
        run: npx gulp build
        working-directory: ${{env.WEB_PROJECT_PATH}}
      - name: Publish
        run: dotnet publish Buttercup.Web.csproj --configuration Release --os linux --arch x64 /t:PublishContainer -p ContainerRepository=${{ env.IMAGE_NAME }}
        working-directory: ${{env.WEB_PROJECT_PATH}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker tag ${{ env.IMAGE_NAME }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:commit-${{ github.sha }}
          docker push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Obtain digest
        run: echo "IMAGE_DIGEST=$(docker images --filter reference=${{ env.IMAGE_NAME }} --format "{{.Digest}}")" >> "$GITHUB_ENV"
      - name: Attest
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ env.IMAGE_DIGEST }}
          push-to-registry: true
